# Singularity arguments
use-singularity: True
singularity-args: "--bind /nfs/turbo/umms-esnitkin/Project_Cauris/Analysis/2024_Pipeline_testing/2024_11_11_funQCD_database/lib/interproscan_data/data/:/opt/interproscan/data/ --bind /nfs/turbo/umms-esnitkin/Project_Cauris/Analysis/2024_Pipeline_testing/2024_11_11_funQCD_database/lib/busco/saccharomycetales/:/opt/databases/saccharomycetales/"
latency-wait: 1000
nolock: True
# make sure at least 8 cores are provided 
cores: 16
# make sure this is equal to the memory provided in config/config.yaml
resources: mem_mb=15000
